require('../models/debt')
require('../models/role')
require('../models/sale')
require('../models/user')
require('../models/store')
require('../models/order')
require('../models/branch')
require('../models/expense')
require('../models/payment')
require('../models/product')
require('../models/category')
require('../models/supplier')
require('../models/customer')
require('../models/activity')
require('../models/purchase')
require('../models/adjustment')
require('../models/debt_history')
require('../models/expense_type')


// require('../models/item')
// require('../models/stock')
// require('../models/route')
// require('../models/truck')
// require('../models/hotel')
// require('../models/device')
// require('../models/service')
// require('../models/freight')
// require('../models/account')
// require('../models/quotation')
// require('../models/attraction')
// require('../models/transaction')
// require('../models/truck_order')
// require('../models/customer_count')
// require('../models/quotation_invoice')